### PR TITLE
fbrem and propagation fix

### PR DESCRIPTION
**Pull request by beaudett**
Hello,

there are two changes in this PR
1) a major bug-fix in the computation of the extrapolation. The charge wasn't properly set.
2) the computation of fbrem for this electrons. This is quite useful to study the properties of the corresponding clusters. 

Thanks
Florian

### CODE REVIEW

**Comment by clelange** [comment]
Hi Florian,

Thanks for this fix. As you know we're planning on moving to a flat ntuple. Can you confirm that this won't pose a problem for you?
I can merge the PR here and then propagate it to the flat ntuple, but I'd prefer to merge the flat ntuple code PR afterwards so that we only work with one ntupliser. Pedja and I will provide some analysis snippets tomorrow for an easy transition.

Cheers,
Clemens

**Comment by clelange** [comment]
There is a bug: Missing fbrem in https://github.com/CMS-HGCAL/reco-ntuples/pull/23/files#diff-15765fecaeef229e305b918c8405f57aL336 (line 336) and fbrem should be declared earlier.
@beaudett Can you please fix it?

**Comment by clelange** [comment]
Also, is -1 a good default value? Doesn't 0 make more sense?

**Comment by beaudett** [comment]
Hello, 
Thanks a lot for spotting this bug. I have inserted  a -1. on line 336. 

About the default value: 0 is physical value for fbrem. It is computed only for electrons, I prefer to put -1 as it clearly shows that it wasn't computed.

Florian

**Pull request merged**
