### PR TITLE
Add gun particle information to produced ntuples

### PR DESCRIPTION
**Pull request by riga**
Changes proposed in this pull-request:

- Added gun particle information to ntuples:
  - PDG id
  - Energy
  - Mass
  - Pt
  - Eta
  - Phi
- Added boolean module option `storeGunParticles`.

The values are stored *per* gun particle shot *per* vertex, thus the vector-in-vector structure.

This could be useful for either trainings to predict the initial gun particle momenta, or for final calibrations.

When merged, I will also update the template in https://github.com/CMS-HGCAL/reco-prodtools/blob/master/templates/partGun_NTUP_template.py.

### CODE REVIEW

**Comment by clelange** [comment]
Looks good to me. Do we really need to store the mass as well? The 4-vector should be fully defined by energy, pT, eta, phi.
The new flag also needs to be propagated to https://github.com/CMS-HGCAL/reco-prodtools/blob/master/templates/partGun_NTUP_template.py

**Comment by riga** [comment]
True. I will remove it and update the PR.

**Comment by clelange** [comment]
Thanks. Please also update the NTUP_template asap.

**Comment by clelange** [comment]
I realised too late that these variables should be defined in https://github.com/CMS-HGCAL/reco-ntuples/blob/master/Definitions.md as well. @riga could you please add a row in a follow-up PR?

**Pull request merged**
