### PR TITLE
Add Electrons to HGCAL Ntuple

### PR DESCRIPTION
**Pull request by rovere**
Changes proposed in this pull-request:

- Add electrons from MultiClusters into the ntuple
- Global reformat of the code using:
```
clang-format -style="{BasedOnStyle: Google, ColumnLimit: 100}"
```
- Consistently name private variables with a trailing `_` for easier readability.
- better visualize the diff introduced by this PR with `?w=1` added.

### CODE REVIEW

**Comment by clelange** [comment]
Hi @rovere, thanks for the PR. I think it's good to `clang-format` the code, like this we can make it a requirement for future PRs. With the global renaming etc. it will take some time to review the changes. It would have been easier with separate commits for each of the changes mentioned. I will not be able to review the PR before next week, since I'll be away until the end of the week, so it would be great if someone else had a look (the rights should be there and @artlbv would be a candidate), otherwise I'll get to it next week.

**Comment by artlbv** [comment]
Hi Clemens,

Since I’m planning in (and already) using this extension, I can take over this review.
I’ll let you know if I get questions.

**Comment by artlbv** [comment]
I had a look at the code and also compared the PR ntuple against the master and here are my conclusions:
* There are no changes for the pre-existing collections
* The new collections also seem fine, but maybe it is worth to add a flag whether to store the new collections, like it is done for the raw rechits and PCA variables here: https://github.com/rovere/reco-ntuples/blob/master/HGCalAnalysis/test/exampleConfig.py#L29-L34. The ntuple size did not change much for electron samples, but it could be easier for those not working with electrons.
* It is indeed hard to review the changes in the code formatting, especially since everything is in one commit. Apart from the new gsfElectron part, I've also found several changes in the headers, like here: https://github.com/CMS-HGCAL/reco-ntuples/pull/51/files?w=1#diff-15765fecaeef229e305b918c8405f57aL16
As I said, nothing seems to have changed for the gen particles and positions, but maybe @rovere could comment on the changes in the include files.

I suggest to add the flag and then merge this PR asap, since the changed format and variable names should go into the master before any further development.

Btw, this PR addresses issue https://github.com/CMS-HGCAL/reco-ntuples/issues/47.

**Comment by rovere** [comment]
@artlbv The shuffling in the headers is just some lexicographical ordering induced by clang-format.
I added the boolean parameter.

**Pull request merged**
